return {
  'ibhagwan/fzf-lua',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  keys = {
    { '<leader><leader>', '<cmd>FzfLua buffers<cr>', desc = 'search open buffers' },
    { '<leader>/', '<cmd>FzfLua blines<cr>', desc = 'search current buffer' },
    { '<leader>ca', '<cmd>FzfLua lsp_code_actions<cr>', desc = 'LSP: [c]ode [a]ctions' },
    { '<leader>gd', '<cmd>FzfLua lsp_definitions<cr>', desc = 'LSP: [g]oto [d]efinition' },
    { '<leader>gD', '<cmd>FzfLua lsp_declarations<cr>', desc = 'LSP: [g]oto [D]eclaration' },
    { '<leader>gt', '<cmd>FzfLua lsp_typedefs<cr>', desc = 'LSP: [g]oto [t]ype definition' },
    { '<leader>gI', '<cmd>FzfLua lsp_implementations<cr>', desc = 'LSP: [g]oto [I]mplementation' },
    { '<leader>gr', '<cmd>FzfLua lsp_references<cr>', desc = 'LSP: [g]oto [r]eferences' },
    { '<leader>ds', '<cmd>FzfLua lsp_document_symbols<cr>', desc = 'LSP: [d]ocument [s]ymbols' },
    { '<leader>s/', '<cmd>FzfLua lines<cr>', desc = '[s]earch open buffers' },
    { '<leader>sb', '<cmd>FzfLua builtin<cr>', desc = '[s]earch [b]uilt-in' },
    { '<leader>sd', '<cmd>FzfLua diagnostics_document <cr>', desc = '[s]earch [d]ocument diagnostics' },
    { '<leader>sf', '<cmd>FzfLua files <cr>', desc = '[s]earch project [f]iles' },
    { '<leader>Sf', '<cmd>FzfLua files no_ignore=true<cr>', desc = '[S]earch all project [f]iles (no ignore)' },
    { '<leader>sg', '<cmd>FzfLua grep<cr>', desc = '[s]earch [g]rep' },
    { '<leader>sG', '<cmd>FzfLua live_grep<cr>', desc = '[s]earch live [G]rep' },
    { '<leader>Sg', '<cmd>FzfLua grep<cr>', desc = '[S]earch [g]rep (no ignore)' },
    { '<leader>SG', '<cmd>FzfLua live_grep no_ignore=true<cr>', desc = '[S]earch live [G]rep (no ignore)' },
    { '<leader>sh', '<cmd>FzfLua help_tags<cr>', desc = '[s]earch [h]elp docs' },
    { '<leader>sk', '<cmd>FzfLua keymaps<cr>', desc = '[s]earch [k]eymaps' },
    { '<leader>sn', '<cmd>FzfLua files cwd=~/.config/nvim/<cr>', desc = '[s]earch [n]eovim files' },
    { '<leader>sr', '<cmd>FzfLua live_resume<cr>', desc = '[s]earch [r]esume' },
    { '<leader>sw', '<cmd>FzfLua grep_cword<cr>', desc = '[s]earch current [w]ord' },
    { '<leader>s.', '<cmd>FzfLua oldfiles<cr>', desc = '[s]earch recent files' },
    { '<leader>ws', '<cmd>FzfLua lsp_workspace_symbols<cr>', desc = 'LSP: [w]orkspace [s]ymbols' },
  },
}
