return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    icons = {
      breadcrumb = '»',
      separator = '➜',
      group = '+',
    },
    plugins = {
      marks = true,
      registers = true,
      spelling = { enabled = true, suggestions = 20 },
      presets = {
        operators = true,
        motions = true,
        text_objects = true,
        windows = true,
        nav = true,
        z = true,
        g = true,
      },
    },
    win = {
      border = 'single',
      padding = { 2, 2, 2, 2 },
    },
    spec = {
      { '<leader>a', group = '[a]i', icon = '󱚟' },
      { '<leader>b', group = '[b]uffer', icon = '󰓩' },
      { '<leader>c', group = '[c]ode', icon = '󰅫' },
      { '<leader>d', group = '[d]iagnostics', icon = '󰒡' },
      { '<leader>f', group = '[f]ile', icon = '󰈔' },
      { '<leader>g', group = '[g]oto/[g]it', icon = '󰊢' },
      { '<leader>m', group = '[m]edia', icon = '󰎄' },
      { '<leader>o', group = '[o]pen', icon = '󰏌' },
      { '<leader>p', group = '[p]lay', icon = '󰊗' },
      { '<leader>q', group = '[q]uick debug', icon = '󰃤' },
      { '<leader>r', group = '[r]un/[r]efactor', icon = '󰑮' },
      { '<leader>s', group = '[s]earch', icon = '󰍉' },
      { '<leader>t', group = '[t]oggle', icon = '󰔡' },
      { '<leader>w', group = '[w]orkspace', icon = '󱂬' },
    },
  },
}
